Dev-FE-1/Toy_Project_3_Team5

src/components/Toast.tsx
토스트메세지 컴포넌트 개발
closes #1 
- 토스트 메세지 개발
- 버튼으로 출력테스트 완료
> [!IMPORTANT]
> 위치나 크기는 추후 조정이 필요하므로 사용시에 변경 바랍니다
- 사용법은 아래 코드를 참고해주세요
<details> <summary> 테스트 코드 Test.tsx</summary>
```typescript
import { useState } from 'react';
import Toast from '@/components/Toast';
const Test = () => {
const [isActive, setIsActive] = useState<boolean>(false);
const toastMsg = '테스트 메세지입니다';
const onClose = () => {
setIsActive(!isActive);
};
const onClick = () => {
setIsActive(!isActive);
};
return (
<div>
<button type='button' onClick={onClick}>
토스트 테스트
</button>
<Toast isActive={isActive} onClose={onClose} toastMsg={toastMsg} />
</div>
);
};
export default Test;
```
</details>
=> [feature] 토스트 메세지 컴포넌트 개발

.gitignore, src/env.d.ts, src/firebase/firbaseConfig.ts, src/hooks/useVideo.ts
**[작업 내용을 간략히 적어주세요]**
firebase config 구성
수정한 내용이나 추가한 기능에 대해 자세히 설명해 주세요.
config에 필요한 apikey등의 정보를 깃에서 빼는게 나을것 같아, 
현재 데이터는 .env라는 파일에 넣어두고 ignore에 등록해놓았습니다.
파이어베이스에서
왼쪽 상단 프로젝트 개요 -> 프로젝트 설정에서 firebaseConfig 변수를 복사하셔서
루트에 '.env' 파일을 만드시고 그곳에 복사하신 코드를 넣으시면 됩니다.
=> Firebase: firebase 환경 설정 #22

src/components/IconButton.tsx, src/components/TextFilter.tsx
TextFilter 컴포넌트 구현
- TextFilter 컴포넌트를 구현했습니다.
- (이미 PR merge 처리된) IconButton 컴포넌트의 네이밍 컨벤션이 맞지 않는 변수명을 수정했습니다.
위와 같습니다.
=> [feature] TextFilter 컴포넌트 구현

src/components/KebabButton.tsx
케밥 버튼 컴포넌트 개발 
- 케밥버튼(점세개 더보기버튼) 컴포넌트 제작
- 바깥 영역 클릭 시 미니모달 닫힘
```
import KebabButton from '@/components/KebabButton';
const App = () => {
const menuItems = [
{
label: '수정',
onClick: () => console.log('수정 클릭'),
},
{
label: '삭제',
onClick: () => console.log('삭제 클릭'),
},
{
label: '상세보기',
onClick: () => console.log('상세보기 클릭'),
},
];
return (
<div>
<KebabButton menuItems={menuItems} />
</div>
);
};
export default App;
```
=> [feature] 케밥 버튼 컴포넌트 개발 

src/components/PopupFilter.tsx
PopupFilter 컴포넌트 구현
- PopupFilter 컴포넌트를 구현했습니다.
- 필터를 제외한 다른 영역을 클릭할 경우, 필터가 비활성화되도록 했습니다.
- 다중 필터 기능이 누락되어 작업 후 반영했습니다.
위와 같습니다.
=> [feature] PopupFilter 컴포넌트 구현

src/components/CheckBox.tsx
체크박스 컴포넌트 구현
- 체크박스 컴포넌트 구현
위와 같습니다.
https://github.com/user-attachments/assets/be5e4a6e-24ef-4ed6-8ff0-d2aa29ff147c
- 아이콘을 찾을 수 없어서 일단 svg로 사용했습니다.
=> [feature] CheckBox 컴포넌트 구현

src/components/Layout.tsx, src/styles/GlobalStyles.tsx
Layout 페이지 스타일링 
Layout 페이지 스타일링하고 글로벌 스타일 수정했습니다.
=> [design] Layout 페이지 스타일링 

src/constants/route.ts, src/mock/following-test.ts, src/pages/common/Following.tsx, src/router/router.tsx
팔로잉 페이지 퍼블리싱
closes #69 
- 팔로잉 페이지 퍼블리싱
- 테스트데이터 분리 (/mock/following-test.ts)
라우팅 경로 수정
- 팔로잉 리스트가 있을 때
- 팔로잉 리스트가 없을 때
- playlist div의 height를 추가로 계산해야합니다. (헤더크기, 네비바 크기를 아직 몰라서..)
=> [feature] 팔로잉 페이지 퍼블리싱

src/pages/playlist/PlayList.tsx, src/pages/playlist/PlayListHome.tsx, src/pages/playlist/PlayListLikes.tsx, src/pages/playlist/PlayListSaved.tsx
=> [design] 마이플리 페이지 퍼블리싱 작업 완료

src/components/Navbar.tsx, src/components/PlaylistCard.tsx, src/pages/common/Home.tsx, src/router/router.tsx
홈(메인) 페이지 UI 퍼블리싱
- 홈(메인) 페이지의 UI 퍼블리싱을 진행했습니다.
- Navbar의 아이콘 간격이 일정하지 않아 수정했습니다.
위와 같습니다.
간단한 UI 퍼블리싱만 진행하였고, 추후 무한 스크롤 및 필터링 기능 연동 예정입니다.
=> [design] 홈(메인) 페이지 UI 퍼블리싱

src/components/Button.tsx
Button 컴포넌트 수정
- props에 type(submit, reset 등)을 추가했습니다.
- LightGray 컬러를 추가했습니다.
위와 같습니다.
=> [fix] Button 컴포넌트 수정

src/pages/profile/ProfileHome.tsx
마이페이지 UI 퍼블리싱
마이페이지 UI 퍼블리싱
위와 같습니다
로그인 기능 구현하다가 로그아웃 기능, 로그인 유지 기능 구현시 프로필 정보가 필요해 먼저 만들게 되었습니다
=> [design] 마이페이지 UI 퍼블리싱

src/components/Header.tsx, src/components/Layout.tsx, src/components/Navbar.tsx, src/pages/common/Following.tsx, src/pages/common/Home.tsx, src/styles/GlobalStyles.tsx
Layout 스타일링 수정 작업
-Header 컴포넌트 스타일링 수정(배경색 추가)
-Layout 컴포넌트 스타일링 수정
=> [fix] Layout 스타일링 수정 작업

src/pages/common/Popular.tsx
popular 스타일링 수정 작업 
**[작업 내용을 간략히 적어주세요]**
1. 인기 페이지를 클릭하면 화면에 스크롤이 생기는 부분을 수정했습니다.
2. playlistCard부분이 스크롤로 아래로 내려가게 끔 수정하였습니다. 
수정한 내용이나 추가한 기능에 대해 자세히 설명해 주세요.
=> [fix] popular 스타일링 수정 작업

src/components/InputBox.tsx
InputBox 컴포넌트 value 상태 업데이트 수정
useEffect를 추가하여 propValue가 변경될 때마다 내부 value 상태 업데이트
위와 같습니다.
=> [fix] InputBox 컴포넌트 수정

package-lock.json, package.json, src/components/Header.tsx
Header 컴포넌트 검색 키워드 기반 라우팅 구현
- Header 컴포넌트 검색창을 이용해 키워드를 입력할 경우 해당 쿼리를 기반으로 라우팅되도록 구현했습니다.
- 미설치된 Firebase 라이브러리를 설치했습니다.
위와 같습니다.
큰 변경점은 없습니다. 누락된 Firebase 라이브러리를 포함시켰습니다.
=> [feature] Header 컴포넌트 검색 키워드 기반 라우팅 구현

src/components/Header.tsx, src/components/Layout.tsx, src/router/router.tsx, src/types/header.ts, src/utils/headerUtils.ts
URL별 헤더타입 체크 로직 추가
- 최종 디자인 기반으로 페이지 별 헤더 분리
=> [refactor] 접속 페이지별 헤더 타입 변경 기능 추가

src/components/InputBox.tsx, src/firebase/firbaseConfig.ts, src/pages/common/SignIn.tsx, src/pages/common/SignUp.tsx, src/stores/useAuthStore.ts
회원가입 UI 퍼블리싱 & 기능 구현
- 회원가입 UI 퍼블리싱
- 아이디, 채널 이름 중복확인 기능 구현 -> 커스텀 훅으로 뺄 예정
- 유효성 검사 기능 구현
- 파이어베이스 uid -> id 로 등록되게 변경
위와 같습니다.
- 추후 TanStack Query 리팩토링 예정입니다.
- 우선 회원가입 기능이 필요하실까봐 기능 구현 완료 후 PR올립니다!
=> [feature] 회원가입 UI 퍼블리싱 & 기능 구현

src/stores/useAuthStore.ts
useAuthStore 전역 상태 관리 데이터 수정
- 기존에 Zustand를 이용해 관리하던 로그인한 사용자의 전역 상태 값을 수정했습니다.
위와 같습니다.
기존 전역 상태 관리 데이터에 userId(로그인 아이디) 외 추가적으로 사용될 전역 상태 데이터를 추가했습니다.
=> [fix] useAuthStore 전역 상태 관리 데이터 수정

src/api/playlistInfo.ts
플레이리스트 관리 api 개발
closes #104 
플레이리스트 Collection CURD API 개발
=> [feature] 플레이리스트 관리 api 개발

src/hooks/usePlaylistActions.ts
플레이리스트 좋아요 기능 및 개수 동기화 로직 수정
- 기존 플레이리스트 좋아요 기능 동작 시 좋아요 개수 동기화가 되지 않던 문제를 수정했습니다.
위와 같습니다.
여러 방법을 시도해보다가 Optimistic Update(낙관적 업데이트) 방식으로 처리하도록 수정했습니다.
=> [fix] 플레이리스트 좋아요 기능 및 개수 동기화 로직 수정

src/components/Comment.tsx, src/components/MiniPlaylist.tsx, src/components/Navbar.tsx, src/components/PlaylistCard.tsx, src/components/Video.tsx, src/components/playlist/AddedVideo.tsx, src/pages/common/Detail.tsx, src/pages/common/Following.tsx, src/pages/common/Popular.tsx, src/pages/common/SignUp.tsx, src/pages/profile/ProfileFollower.tsx, src/pages/profile/ProfileFollowing.tsx, src/pages/profile/ProfileUpdate.tsx
최종 스타일 통합 
1. 회원가입 페이지: 중복검사 버튼 어긋나는거 해결
2. 플리카드 라지 사이즈 조절
3. 프로필 수정: 중복검사 버튼 어긋나는거 해결
4. 상세페이지: 피그마 디자인으로 수정
5. 팔로잉 팔로워 상세: 폰트사이즈 조절
6. 팔로잉 페이지: 프로필 가운데 정렬
7. Navbar: 마이플리 url userid 이동안되는거 수정
폰트사이즈, 간격, 정렬 같은 요소들 조정했습니다.
=> [design] 최종 스타일 통합 

src/components/PlaylistCard.tsx, src/pages/playlist/PlayListAdd.tsx, src/pages/playlist/PlayListHome.tsx
마이플리 페이지 버그픽스 
- 마이플리 페이지(홈): 플리 삭제 시 실시간 업데이트 안되는 문제 처리
- 플레이리스트 추가 버튼 하단 고정 + 플레이리스트 추가페이지 스타일링 수정(디자인 통합할때 까먹음)
- 플레이리스트 생성페이지에서는 카드 컴포넌트 클릭할수없게 처리
=> [bug] 마이플리 페이지 버그픽스 

src/pages/common/SignIn.tsx
구글 로그인 버그픽스
- 구글 로그인시 로그인만 되고 사용자 정보는 파이어베이스에 업데이트 되지 않는 버그 수정
위와 같습니다.
https://github.com/user-attachments/assets/3c8bf407-ce99-4e1b-824a-491b8f124407
=> [bug] 구글 로그인 버그픽스

src/api/chennelInfo.ts, src/hooks/useFollowToggle.ts, src/pages/profile/ProfileFollower.tsx, src/pages/profile/ProfileFollowing.tsx
팔로잉 uid로 들어가는 문제 해결 
1. 팔로잉 uid로 들어가는 문제 해결 
2. 팔로잉,팔로워 목록 버튼 스타일링 수정
=> [bug] 팔로잉 uid로 들어가는 문제 해결 

src/hooks/useFollowToggle.ts
useFollowToggle 훅 수정
영상 상세페이지에서도 useFollowToggle 연동되도록 훅 수정
영상디테일페이지에서 이렇게만 바꾸면 연동됩니다!
```
const { isFollowing, handleFollowToggle } = useFollowToggle(
ownerInfo?.userId
);
```
=> [bug] useFollowToggle 훅 수정

src/components/PlaylistCard.tsx, src/hooks/useDetailForm.ts, src/hooks/usePlaylistActions.ts, src/pages/common/Detail.tsx, src/pages/playlist/PlayListAdd.tsx, src/pages/playlist/PlayListEdit.tsx
토스트 메세지에 맞는 status를 붙여줬습니다.
closes #166 
토스트 메세지에 맞는 status를 불러오도록 수정 (#166)
=> [fix] 토스트 메세지에 맞는 status를 불러오도록 수정

src/api/followingPlaylists.ts, src/hooks/useTagFetch.ts, src/pages/common/Following.tsx, src/pages/profile/ProfileFollower.tsx, src/pages/profile/ProfileFollowing.tsx
**[작업 내용을 간략히 적어주세요]**
1 .타인의 프로필로 팔로잉 팔로워 목록 접근시 삭제 버튼 기능이 가능한 버그 해결
2. 비공개 영상이 팔로잉 페이지 인기 페이지에 올라오는 버그 해결
수정한 내용이나 추가한 기능에 대해 자세히 설명해 주세요.
수정된 화면 또는 기능을 시연할 수 있는 스크린샷
https://github.com/user-attachments/assets/26ee1947-2071-41c0-b3b7-310afc296141
을 첨부할 수 있습니다.
=> [bug] 팔로잉 팔로워 인기 페이지 버그 해결

src/api/followingPlaylists.ts, src/hooks/useChannel.ts, src/hooks/useList.ts, src/hooks/useTagFetch.ts, src/pages/common/Following.tsx, src/pages/profile/ProfileFollower.tsx, src/pages/profile/ProfileFollowing.tsx
**[작업 내용을 간략히 적어주세요]**
팔로잉 팔로워 리스트 채널이름으로 변경
수정한 내용이나 추가한 기능에 대해 자세히 설명해 주세요.
=> [bugfix]팔로잉 팔로워 리스트 채널이름으로 변경

src/stores/useAuthStore.ts
로그아웃시 처음 로그인 정보(isFirstLogin) 초기화 되는 문제 해결
INIT_VALUES에서 isFirstLogin제거
위와 같습니다.
=> [bug] 로그아웃시 처음 로그인 정보(isFirstLogin) 초기화 되는 문제 해결

src/api/homePlaylists.ts, src/api/searchPlaylists.ts, src/components/Button.tsx, src/hooks/useHomePlaylist.ts, src/hooks/useSearchPlaylist.ts, src/pages/common/Home.tsx, src/pages/common/Search.tsx
코드 리뷰 수정사항 반영
- 오타로 인한 컨벤션 미준수 사항을 반영했습니다.
- 불필요한 타입 지정 방식을 수정했습니다.
- Home, Search 페이지의 무한 스크롤 관련 객체 선언 위치를 조정했습니다.
- Home, Search 페이지에 초기 로딩 컴포넌트 로직을 추가하고, 기존에 존재하던 폴더 이미지를 제거했습니다.
- Button 컴포넌트의 CSS 스타일 속성 처리 방식을 수정했습니다.
- 특정 API의 코드 내 혼재되어 있던 API, Hook 로직을 분리했습니다.
위와 같습니다.
=> [refector] 코드 리뷰 수정사항 반영
